source "https://rubygems.org"
# Add dependencies required to use your gem here.
# Example:
#   gem "activesupport", ">= 2.3.5"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
<% development_dependencies.each do |name, version| %>
  gem "<%= name %>", "<%= version %>"
<% end %>
end
