# Add dependencies required to use your gem here.
group :runtime do
  #gem 'bundler', '>= 0.9.5'
end

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
<% (development_dependencies + testing_framework_base.development_dependencies).each do |name, version| %>
  gem "<%= name %>", "<%= version %>"
<% end %>
end
