require 'rubygems'

<% rakefile_head_snippet_plugins.each do |plugin| %>
<%= plugin.rakefile_head_snippet %>
<% end %>

<%= render_template 'jeweler_tasks.erb' %>

<%= render_template 'other_tasks.erb' %>
