require 'jeweler/commands/release'
require 'jeweler/commands/write_gemspec'
require 'jeweler/commands/version/base'
require 'jeweler/commands/version/bump_major'
require 'jeweler/commands/version/bump_minor'
require 'jeweler/commands/version/bump_patch'
require 'jeweler/commands/version/write'
